Repository IO500/webpage, pull requests merged in 2021-11, with the labels that each got.

#192 Update NRCTM institution name
  sql/2021-11-19-update-NRCTM-name.sql
Labels: submission

#193 Create 2021-11-22-update-CMKL-name.sql
  sql/2021-11-22-update-CMKL-name.sql
Labels: submission

#196 Create 2021-11-26-update-ocean-stor-name.sql
  sql/2021-11-26-update-ocean-stor-name.sql
Labels: submission

#194 Update news page for SC21 release
  templates/Pages/news.php
Labels: news

#195 Fix the list name and closes #171
  templates/Pages/news.php
Labels: bug
